### ISSUE TITLE
Can't Install the app

### ISSUE THREAD

**Issue by Sualeheen** [iamharshdev/TheBoringNotch#31]
[
<img width="248" alt="Screenshot 2024-08-10 at 3 47 37 PM" src="https://github.com/user-attachments/assets/3ae2d3d0-6ac3-4113-8721-886416906b7d">
](url)

**Comment by iamharshdev** [comment]
Click okay. Go to system settings > Privacy & Security > Scroll to bottom and you’ll see option to open the app anyway just click that retry opening the app again by searching boringnotch in spotlight. Thanks
